### PR TITLE
Refactor easy mode apps

### PR DESCRIPTION
**Pull request by danlamanna**
@curtislisle Take a look and give these a spin, some of these are in various states of operation, but no worse than how they were (I think). I imagine after you take a look there will be certain ones that need some level of tweaking to work 100%.

### CODE REVIEW

**Comment by curtislisle** [comment]
Thanks, Dan. I'll take 'me for a spin. 😀

**Comment by curtislisle** [comment]
dumb question.  remind me please where to put the static directory again?  I am on a different system than the one I installed on, so I need a refresher on the part,  Thx

**Comment by danlamanna** [comment]
In the root flow directory, so `/flow/static/foo` will let you append `/foo` to your url. I think this might be `/opt/flow/static/foo` in the Vagrant setup.

**Comment by curtislisle** [comment]
What changes are in this PR that make it not compatible to merge with master automagically?

**Comment by danlamanna** [comment]
I updated this branch (since the other was merged). I'm pretty sure certain apps need to be tweaked though, so definitely try to break them and let me know if that's the case before merging.

**Comment by curtislisle** [comment]
Thanks, Dan! I know I've been quiet lately . I'm running family errands today. I'll mess with the apps over the weekend. I will also forward you my login information for the DNS server so we can look at the configuration. If we fix the DNS to point directly to the instance, will that help us automatically update the instance from scripts more easily?

**Comment by danlamanna** [comment]
Not necessarily, but it would be nice if we could serve the instance at the domain rather than the IP (should it ever change).

**Pull request merged**
